### ISSUE TITLE
Error in the docs for tailwind.config.js example.

### ISSUE THREAD

**Issue by mdochdev** [houseabsolute/tailwindcss-to-rust#5]
When matching the M![M...., C....] the following causes an issue:
```
let pieces = m.slice(1, m.length);
```
The data contained in m is:
```
[
  'M::dark, C::typ::text_green_100',
  'M::dark, ',
  'dark',
  'text_green_100',
  index: 3,
  input: 'M![M::dark, C::typ::text_green_100],',
  groups: undefined
]
```

So the output ends up being built like: `["M::dark, dark", ":dark:text-green-100", "text-green-100"]` by changing the 1 to a 2 in the slice it fixes the problem.
eg the output is: `[ 'dark:text-green-100', 'text-green-100' ]`

Without this fix the Modules are ignored in creating the css.

There is a further issue with the `mod_re` parsing expression where it does not support more than one Module. I do not have an example fix for the regex for this one.

**Comment by autarch** [comment]
I updated this code and the docs for the latest release. I also wrote some end-to-end tests for this and I can confirm that it works. Obviously, the JS code you use for the tailwind config will vary depending on exactly how you use the generated code and macros in your own code.
